ALTER TABLE CONFIGURATIONS DROP CONSTRAINT FK_CONFIGURATIONS_USER_ID
ALTER TABLE CONFIGURATIONS DROP CONSTRAINT FK_CONFIGURATIONS_CONFIG_ITEM_ID
ALTER TABLE CONFIGURATIONS DROP CONSTRAINT UNQ_CONFIGURATIONS_0
ALTER TABLE CONFIGURATION_ITEMS DROP CONSTRAINT UNQ_CONFIGURATION_ITEMS_0
ALTER TABLE SESSION_REGISTRY DROP CONSTRAINT FK_SESSION_REGISTRY_PRINCIPAL
ALTER TABLE EXTENSIONVALUE DROP CONSTRAINT FK_EXTENSIONVALUE_EXTN_ID
ALTER TABLE TRANSACTIONS DROP CONSTRAINT FK_TRANSACTIONS_PORTFOLIO_ID
ALTER TABLE TRANSACTIONS DROP CONSTRAINT FK_TRANSACTIONS_INSTRUMENT_ID
ALTER TABLE TRANSACTIONS DROP CONSTRAINT FK_TRANSACTIONS_BROKER_ID
ALTER TABLE STOCK_PREFERENCE DROP CONSTRAINT FK_STOCK_PREFERENCE_USER_ID
ALTER TABLE STOCK_PREFERENCE DROP CONSTRAINT FK_STOCK_PREFERENCE_STOCK_ID
ALTER TABLE PORTFOLIO DROP CONSTRAINT FK_PORTFOLIO_WEALTH_CONTEXT_ID
ALTER TABLE INSTRUMENTS DROP CONSTRAINT UNQ_INSTRUMENTS_0
ALTER TABLE HOLDINGS DROP CONSTRAINT FK_HOLDINGS_BROKER_ID
ALTER TABLE HOLDINGS DROP CONSTRAINT FK_HOLDINGS_PORTFOLIO_ID
ALTER TABLE HOLDINGS DROP CONSTRAINT FK_HOLDINGS_INSTRUMENT_ID
ALTER TABLE HOLDINGS DROP CONSTRAINT FK_HOLDINGS_WEALTH_CONTEXT_ID
ALTER TABLE HOLDINGS DROP CONSTRAINT UNQ_HOLDINGS_0
ALTER TABLE EQUITIES DROP CONSTRAINT FK_EQUITIES_INSTRUMENT_ID
ALTER TABLE BROKERAGE_STRUCTURES DROP CONSTRAINT UNQ_BROKERAGE_STRUCTURES_0
ALTER TABLE USER_WEALTH_CONTEXT DROP CONSTRAINT FK_USER_WEALTH_CONTEXT_USER_FK
ALTER TABLE MTMS DROP CONSTRAINT FK_MTMS_INSTRUMENT_ID
ALTER TABLE MTMS DROP CONSTRAINT UNQ_MTMS_0
ALTER TABLE USER_AUTHORITIES DROP CONSTRAINT FK_USER_AUTHORITIES_AUTHORITY_ID
ALTER TABLE USER_AUTHORITIES DROP CONSTRAINT FK_USER_AUTHORITIES_USER_ID
ALTER TABLE FAV_STOCKS DROP CONSTRAINT FK_FAV_STOCKS_USER_ID
ALTER TABLE FAV_STOCKS DROP CONSTRAINT FK_FAV_STOCKS_STOCK_ID
DROP TABLE USERS
DROP TABLE CONFIGURATIONS
DROP INDEX INDEX_CONFIGURATION_ITEMS_CONFIG_ITEM_KEY
DROP TABLE CONFIGURATION_ITEMS
DROP TABLE SESSION_REGISTRY
DROP TABLE AUTHORITIES
DROP TABLE EXTENSIONS
DROP TABLE EXTENSIONVALUE
DROP TABLE WM_PARAMS
DROP TABLE TRANSACTIONS
DROP TABLE STOCK_PREFERENCE
DROP TABLE PORTFOLIO
DROP TABLE INSTRUMENTS
DROP TABLE HOLDINGS
DROP TABLE EQUITIES
DROP TABLE BROKERAGE_STRUCTURES
DROP TABLE USER_WEALTH_CONTEXT
DROP TABLE MTMS
DROP TABLE JOB_UNIQUE_INSTANCE
DROP TABLE USER_AUTHORITIES
DROP TABLE FAV_STOCKS
DELETE FROM ID_GEN WHERE ID_NAME = 'HOLDING_SEQ'
DELETE FROM ID_GEN WHERE ID_NAME = 'FAV_STOCK_SEQ'
DELETE FROM ID_GEN WHERE ID_NAME = 'INSTRUMENT_SEQ'
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'AUTH_GEN'
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'WM_PARAMS_GEN'
DELETE FROM ID_GEN WHERE ID_NAME = 'TXN_SEQ'
DELETE FROM ID_GEN WHERE ID_NAME = 'BROKERAGE_SEQ'
DELETE FROM ID_GEN WHERE ID_NAME = 'FOLIO_SEQ'
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'JOB_UNIQ_GEN'
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'EXTENSION_GEN'
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'CONFIG_ITEM_GEN'
DELETE FROM ID_GEN WHERE ID_NAME = 'MTM_SEQ'
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'CONFIG_GEN'
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'EXTN_VAL_GEN'
DELETE FROM ID_GEN WHERE ID_NAME = 'WEALTH_CONTEXT_SEQ'
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SESSION_REGISTRY_GEN'
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'USER_GEN'
