ALTER TABLE CONFIGURATIONS DROP CONSTRAINT FK_CONFIGURATIONS_USER_ID
ALTER TABLE CONFIGURATIONS DROP CONSTRAINT FK_CONFIGURATIONS_CONFIG_ITEM_ID
ALTER TABLE CONFIGURATIONS DROP CONSTRAINT UNQ_CONFIGURATIONS_0
ALTER TABLE CONFIGURATION_ITEMS DROP CONSTRAINT UNQ_CONFIGURATION_ITEMS_0
ALTER TABLE SESSION_REGISTRY DROP CONSTRAINT FK_SESSION_REGISTRY_PRINCIPAL
ALTER TABLE EXTENSIONVALUE DROP CONSTRAINT FK_EXTENSIONVALUE_EXTN_ID
ALTER TABLE EXPENSES DROP CONSTRAINT FK_EXPENSES_TYPE_ID
ALTER TABLE EXPENSES DROP CONSTRAINT FK_EXPENSES_USER_EXP_FK
ALTER TABLE EXPENSE_TYPES DROP CONSTRAINT FK_EXPENSE_TYPES_USER_EXP_FK
ALTER TABLE EXPENSE_TYPES DROP CONSTRAINT UNQ_EXPENSE_TYPES_0
ALTER TABLE USER_EXPENSES DROP CONSTRAINT FK_USER_EXPENSES_USER_FK
ALTER TABLE FORECAST_EXPENSE DROP CONSTRAINT FK_FORECAST_EXPENSE_USER_EXP_FK
ALTER TABLE USER_AUTHORITIES DROP CONSTRAINT FK_USER_AUTHORITIES_AUTHORITY_ID
ALTER TABLE USER_AUTHORITIES DROP CONSTRAINT FK_USER_AUTHORITIES_USER_ID
DROP TABLE USERS
DROP TABLE CONFIGURATIONS
DROP INDEX INDEX_CONFIGURATION_ITEMS_CONFIG_ITEM_KEY
DROP TABLE CONFIGURATION_ITEMS
DROP TABLE SESSION_REGISTRY
DROP TABLE AUTHORITIES
DROP TABLE EXTENSIONS
DROP TABLE EXTENSIONVALUE
DROP TABLE WM_PARAMS
DROP TABLE EXPENSES
DROP TABLE EXPENSE_TYPES
DROP TABLE USER_EXPENSES
DROP TABLE FORECAST_EXPENSE
DROP TABLE USER_AUTHORITIES
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'EXTENSION_GEN'
DELETE FROM ID_GEN WHERE ID_NAME = 'FORECAST_SEQ'
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'USER_GEN'
DELETE FROM ID_GEN WHERE ID_NAME = 'USER_EXP_SEQ'
DELETE FROM ID_GEN WHERE ID_NAME = 'EMP_SEQ'
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'CONFIG_GEN'
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SESSION_REGISTRY_GEN'
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'CONFIG_ITEM_GEN'
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'EXTN_VAL_GEN'
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'AUTH_GEN'
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'WM_PARAMS_GEN'
DELETE FROM ID_GEN WHERE ID_NAME = 'EXP_TYPE_SEQ'
